services:
  ununknown:
    build: .
    ports:
      - "7331:7331"
    environment:
      RUST_LOG: info
      UNUNKNOWN_ACOUSTID_API_KEY: AzMVFgUFfS
      UNUNKNOWN_MUSICBRAINZ_USER_AGENT: Ununknown/0.4.0 (artamrjk@gmail.com)}
    volumes:
      - ./music/input:/music/input
      - ./music/output:/music/output
      - ./cache:/cache
    restart: unless-stopped
