services:
  ununknown:
    build:
      context: .
    ports:
      - "7331:7331"
    environment:
      UNUNKNOWN_DB: /cache/ununknown.sqlite
      UNUNKNOWN_INPUT_DIR: /music/input
      UNUNKNOWN_OUTPUT_DIR: /music/output
    volumes:
      - ./.local/cache:/cache
      - ./.local/input:/music/input
      - ./.local/output:/music/output
