pub mod acoustid;
pub mod audd;
pub mod audiomack;
pub mod cover_art_archive;
pub mod deezer;
pub mod discogs;
pub mod genius;
pub mod itunes;
pub mod lastfm;
pub mod musicbrainz;
pub mod navahang;
pub mod radiojavan;
pub mod shazam;
pub mod songrec;
pub mod soundcloud;
pub mod spotify;
pub mod theaudiodb;
pub mod wikidata;
pub mod youtube;

pub use crate::domain::credits::ArtistCredit;
pub use crate::types::{ArtworkCandidate, Candidate};
